- name: Setup MongoDB
  hosts: db
  become: true

  tasks:
    - name: Install MongoDB
      apt:
        name: mongodb
        state: present
        update_cache: yes

    - name: Ensure MongoDB is running
      service:
        name: mongodb
        state: started
        enabled: yes
